package com.st10361554.prog7314_ice_task_3.models

import com.google.gson.annotations.SerializedName

/**
 * Data class representing the response received from the chatbot API.
 *
 * This model provides structured access to all important elements returned by the chatbot,
 * including the response text, any citations, the number of documents used, and categories referenced.
 *
 * @property text The main message or reply generated by the chatbot.
 * @property citations A list of [Citation] objects, representing referenced sources in the response.
 * @property documentsUsed The total number of documents the chatbot used to formulate the response.
 * @property categoriesReferenced A list of categories associated with the sources or logic used in the response.
 */
data class ChatbotResponse(
    @SerializedName("text")
    val text: String, // The main chatbot response text.

    @SerializedName("citations")
    val citations: List<Citation>, // List of citations referenced in the response.

    @SerializedName("documentsUsed")
    val documentsUsed: Int, // Number of documents used to generate the response.

    @SerializedName("categoriesReferenced")
    val categoriesReferenced: List<String> // Categories referenced in the response.
)
